backend:
  image:
    repository: hocommerce8fd771c6.azurecr.io/proj-backend
    tag: "7f6d37086b6b0634683ffd051d8a231823395dfe"
    pullPolicy: IfNotPresent

  config:
    FLASK_ENV: "production"

frontend:
  image:
    repository: hocommerce8fd771c6.azurecr.io/proj-frontend
    tag: "7f6d37086b6b0634683ffd051d8a231823395dfe"
    pullPolicy: IfNotPresent

database:
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent

  storage:
    size: 32Gi
    className: homeoffice-azure-standard-ssd
    createClass: true