backend:
  replicas: 1

  image:
    repository: proj-backend
    tag: health-v1
    pullPolicy: Never

  service:
    port: 5000
    targetPort: 5000

  config:
    DB_HOST: "db"
    DB_PORT: "5432"
    FLASK_ENV: "development"

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

frontend:
  replicas: 1

  image:
    repository: proj-frontend
    tag: latest
    pullPolicy: Never

  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000

database:
  image:
    repository: postgres
    tag: "15"
    pullPolicy: Never