{{- if .Values.database.storage.createClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.database.storage.className | quote }}
provisioner: disk.csi.azure.com
parameters:
  skuName: StandardSSD_LRS
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{- end }}